# Generated by Django 5.0.1 on 2024-01-16 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Non_sheduled_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('from_time', models.DateTimeField(null=True)),
                ('to_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/accounts/pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=255, null=True)),
                ('from_time', models.DateTimeField(null=True)),
                ('to_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='adult_price',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='age_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='child_price',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='gathering_place',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='gatherring_place_location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='route_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='type',
            field=models.CharField(choices=[('group', 'group'), ('individual', 'individual')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='way_to_travel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='what_is_included',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='what_is_not_included',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toursapp.location'),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='pictures',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toursapp.picture'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.IntegerField(null=True)),
                ('non_sheduled_dates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toursapp.non_sheduled_dates')),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toursapp.week')),
            ],
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='toursapp.schedule'),
        ),
    ]
