# Generated by Django 5.0.1 on 2024-01-17 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0003_waytotravel_alter_non_sheduled_dates_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='non_sheduled_dates',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='week',
        ),
        migrations.RemoveField(
            model_name='tourmodel',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='tourmodel',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='tourmodel',
            name='schedule',
        ),
        migrations.AddField(
            model_name='location',
            name='tourkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toursapp.tourmodel'),
        ),
        migrations.AddField(
            model_name='picture',
            name='tourkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toursapp.tourmodel'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tourkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toursapp.tourmodel'),
        ),
        migrations.AddField(
            model_name='week',
            name='schedulekey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toursapp.schedule'),
        ),
        migrations.CreateModel(
            name='Nonsheduleddates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('from_time', models.DateTimeField(auto_now=True, null=True)),
                ('to_time', models.DateTimeField(auto_now=True, null=True)),
                ('schedulekey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='toursapp.schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='Non_sheduled_dates',
        ),
    ]
