# Generated by Django 5.0.1 on 2024-01-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0006_alter_location_tourkey_alter_week_schedulekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsheduleddates',
            name='schedulekey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Non_sheduled_dates', to='toursapp.schedule'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='tourkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='toursapp.tourmodel'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tourkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='toursapp.tourmodel'),
        ),
        migrations.AlterField(
            model_name='week',
            name='schedulekey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week', to='toursapp.schedule'),
        ),
    ]
