# Generated by Django 5.0.1 on 2024-01-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0007_alter_nonsheduleddates_schedulekey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsheduleddates',
            name='schedulekey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='non_sheduled_dates', to='toursapp.schedule'),
        ),
    ]
