# Generated by Django 5.0.1 on 2024-01-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0008_alter_nonsheduleddates_schedulekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonsheduleddates',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='nonsheduleddates',
            name='from_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='nonsheduleddates',
            name='to_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='from_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='to_time',
            field=models.DateTimeField(null=True),
        ),
    ]
