# Generated by Django 5.0.1 on 2024-01-17 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0009_alter_nonsheduleddates_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='tourkey',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='toursapp.tourmodel'),
        ),
    ]
