# Generated by Django 5.0.1 on 2024-01-17 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0010_remove_schedule_tourkey_alter_schedule_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='tour',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='toursapp.tourmodel'),
        ),
    ]
