# Generated by Django 5.0.1 on 2024-01-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0011_alter_schedule_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='tour',
            new_name='tourap',
        ),
    ]
