# Generated by Django 5.0.1 on 2024-01-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0012_rename_tour_schedule_tourap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='tourap',
            new_name='tourkey',
        ),
    ]
