# Generated by Django 5.0.1 on 2024-01-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0013_rename_tourap_schedule_tourkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='tourkey',
        ),
        migrations.AddField(
            model_name='schedule',
            name='tour',
            field=models.IntegerField(null=True),
        ),
    ]
