# Generated by Django 5.0.1 on 2024-01-17 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0016_alter_schedule_tourkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='tourkey',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='toursapp.tourmodel'),
        ),
    ]
