# Generated by Django 5.0.1 on 2024-01-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toursapp', '0017_remove_schedule_tourkey_alter_schedule_tour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='LocationModel',
        ),
        migrations.RenameModel(
            old_name='Nonsheduleddates',
            new_name='NonsheduleddatesModel',
        ),
        migrations.RenameModel(
            old_name='Picture',
            new_name='PictureModel',
        ),
        migrations.RenameModel(
            old_name='Schedule',
            new_name='ScheduleModel',
        ),
        migrations.RenameModel(
            old_name='WayToTravel',
            new_name='WayToTravelModel',
        ),
        migrations.RenameModel(
            old_name='Week',
            new_name='WeekModel',
        ),
    ]
